variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CI_BUILD_NUMBER: $(Build.BuildId)
  BRANCH_NAME: $(Build.SourceBranchName)
  TAG_NAME: $(Build.SourceBranchName)
  SDK_VERSION: 3.x

trigger:
  branches:
    exclude:
      - '*'

pr: none

schedules:
  - cron: "0 12 * * 0"
    displayName: "Weekly fuzz"
    branches:
      include:
        - master
    always: true

stages:
  - stage: Base64
    jobs:
      - template: jobs/fuzzing.yml
        parameters:
          method: Base64_Default_Decode

  - stage: Base64Url
    dependsOn: [] # break sequential dependency
    jobs:
      - template: jobs/fuzzing.yml
        parameters:
          method: Base64_Url_Decode
