parameters:
  name: ''
  vmImage: ''
  dependsOn: ''

jobs:
  - job: ${{ parameters.name }}
    dependsOn:
      - ${{ parameters.dependsOn }}
    condition: and( succeeded(), eq( variables['Build.SourceBranch'], 'refs/heads/master' ) )
    pool:
      vmImage: ${{ parameters.vmImage }}
    timeoutInMinutes: 0     # 360 minutes
    steps:
      - task: DotNetCoreInstaller@0
        inputs:
          packageType: sdk
          version: $(SDK_VERSION)
      
      - bash: |
          chmod u+x *.sh
          ./run-benchmarks.sh

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: 'perf/gfoidl.Base64.Benchmarks/bin/Release/netcoreapp3.0/BenchmarkDotNet.Artifacts/results'
          artifactName: '${{ parameters.name }}'
