parameters:
  name: ''
  vmImage: ''

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    timeoutInMinutes: 0     # 360 minutes
    steps:
      # .NET Core 3 SDK is pre-installed
      #- task: UseDotNet@2
      #  displayName: 'Use dotnet sdk 3.x'
      #  inputs:
      #    version: $(SDK_VERSION)
      #    includePreviewVersions: true

      - bash: |
          chmod u+x *.sh
          ./run-benchmarks.sh

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: 'perf/gfoidl.Base64.Benchmarks/bin/Release/netcoreapp3.0/BenchmarkDotNet.Artifacts/results'
          artifactName: '${{ parameters.name }}'
