parameters:
  name: ''
  vmImage: ''
  dependsOn: ''

jobs:
  - job: ${{ parameters.name }}
    dependsOn:
      - ${{ parameters.dependsOn }}
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.Reason'], 'Schedule'))
    pool:
      vmImage: ${{ parameters.vmImage }}
    timeoutInMinutes: 0     # 360 minutes
    steps:
      - bash: |
          chmod u+x *.sh
          export BENCH_FX=net461
          ./run-benchmarks.sh

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: 'perf/gfoidl.Base64.Benchmarks/bin/Release/net461/BenchmarkDotNet.Artifacts/results'
          artifactName: '${{ parameters.name }}'
