parameters:
  name: ''
  vmImage: ''

jobs:
  - job: ${{ parameters.name }}
    displayName: '${{ parameters.name }} build and test'
    pool:
      vmImage: ${{ parameters.vmImage }}
    strategy:
      matrix:
        debug-build:
          BUILD_CONFIG: Debug
        release-build:
          BUILD_CONFIG: Release
    steps:
      - task: DotNetCoreInstaller@0
        inputs:
          packageType: sdk
          version: $(SDK_VERSION)
        condition: eq( variables['Agent.OS'], 'Windows_NT' )

      - bash: |
          curl -o dotnet-install.sh https://dot.net/v1/dotnet-install.sh
          mkdir dotnet
          chmod u+x ./dotnet-install.sh
          ./dotnet-install.sh --install-dir $(pwd)/dotnet -v $SDK_VERSION
          ./dotnet-install.sh --install-dir $(pwd)/dotnet -v 2.1.500
          rm $(pwd)/dotnet-install.sh
          export PATH="$(pwd)/dotnet:$PATH"

          echo 'installed sdks:'
          dotnet --list-sdks
          echo "-------------------------------------------------"
        displayName: 'installing .net core sdks'
        condition: ne( variables['Agent.OS'], 'Windows_NT' )

      - bash: |
          export PATH="$(pwd)/dotnet:$PATH"
          echo 'installed sdks:'
          dotnet --list-sdks
          echo "-------------------------------------------------"

          chmod u+x ./build.sh
          ./build.sh build $BUILD_CONFIG
        displayName: build

      - bash: |
          export PATH="$(pwd)/dotnet:$PATH"
          echo 'installed sdks:'
          dotnet --list-sdks
          echo "-------------------------------------------------"

          ./build.sh test $BUILD_CONFIG
        displayName: test

      - bash: |
          echo 'installed sdks:'
          dotnet --list-sdks
          echo "-------------------------------------------------"

          ./build.sh pack
        displayName: pack
        condition: and( succeeded(), eq( variables['Agent.OS'], 'Windows_NT' ), eq( variables['BUILD_CONFIG'], 'Release' ) )

      - task: PublishTestResults@2
        inputs:
          testRunner: VSTest
          testResultsFiles: '**/*.trx'

      - task: PublishBuildArtifacts@1
        condition: and( succeeded(), eq( variables['Agent.OS'], 'Windows_NT' ), eq( variables['BUILD_CONFIG'], 'Release' ), ne( variables['Build.Reason'], 'PullRequest' ) )
        inputs:
          pathtoPublish: 'NuGet-Packed'
          artifactName: 'NuGet-Packed'
