parameters:
  name: ''
  vmImage: ''

jobs:
  - job: ${{ parameters.name }}
    displayName: '${{ parameters.name }} build and test'
    dependsOn:
      - linux
      - windows
      - mac
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - task: DotNetCoreInstaller@0
        inputs:
          packageType: sdk
          version: 3.0.100-preview-009765

      - bash: |
          cd demo/gfoidl.Base64.Demo
          dotnet run
