parameters:
  name: ''
  vmImage: ''

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      # .NET Core 3 SDK is pre-installed
      #- task: UseDotNet@2
      #  displayName: 'Use dotnet sdk 3.x'
      #  inputs:
      #    version: $(SDK_VERSION)
      #    includePreviewVersions: true

      - bash: |
          cd demo/gfoidl.Base64.Demo
          dotnet run
