parameters:
  name: ''
  vmImage: ''
  dependsOn: ''

jobs:
  - job: ${{ parameters.name }}
    dependsOn:
      - ${{ parameters.dependsOn }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - task: DotNetCoreInstaller@0
        inputs:
          packageType: sdk
          version: $(SDK_VERSION)

      - bash: |
          cd demo/gfoidl.Base64.Demo
          dotnet run
