parameters:
  method: ''

jobs:
  - job: ${{ parameters.method }}
    pool:
      vmImage: 'ubuntu-18.04'
    timeoutInMinutes: 0     # 360 minutes
    steps:
      - task: UseDotNet@2
        displayName: 'Use dotnet sdk 3.x'
        inputs:
          version: $(SDK_VERSION)
          includePreviewVersions: true
      
      - bash: |
          cd fuzz
          chmod +x *.sh
          sudo ./init-system.sh
        displayName: pre-requisites
      
      - bash: |
          cd fuzz
          ./setup.sh
        displayName: setup

      - bash: |
          cd fuzz
          ./init.sh
        displayName: init

      - bash: |
          cd fuzz
          ./run.sh $(TIMEOUT) ${{ parameters.method }}
        displayName: run          

      - task: PublishBuildArtifacts@1
        condition: failed()
        inputs:
          pathtoPublish: 'fuzz/findings/crashes'
          artifactName: '${{ parameters.method }}'
