name: Auto merge PR
on:
  pull_request:
    types: [labeled]
jobs:
  Run Actions:
    runs-on: [ubuntu-latest]
    steps:
    - name: Automatically merge PR
      uses: plm9606/automerge_actions@1.0.1
      with:
        label-name: automerge
        github-token: ${{ secrets.GITHUB_TOKEN }}
